import os

DEFAULT_LIMIT: int = 5


# ---- DOMAINS ---- #
MARKET_DOMAIN = "market"
ECONOMICS_DOMAIN = "economics"
INSTRUMENT_DOMAIN = "instrument"
FUNDAMENTALS_DOMAIN = "fundamentals"
TECHNICALS_DOMAIN = "technicals"
COMPANY_DOMAIN = "company"
COMMODITIES_DOMAIN = "commodities"
FX_DOMAIN = "fx"
CRYPTO_DOMAIN = "crypto"
DOMAINS: list = [
    MARKET_DOMAIN,
    ECONOMICS_DOMAIN,
    INSTRUMENT_DOMAIN,
    FUNDAMENTALS_DOMAIN,
    TECHNICALS_DOMAIN,
    COMPANY_DOMAIN,
    COMMODITIES_DOMAIN,
    FX_DOMAIN,
    CRYPTO_DOMAIN,
]

# Domain execution order for orchestration (instrument must run first to populate universe)
DOMAIN_EXECUTION_ORDER: tuple[str, ...] = (
    INSTRUMENT_DOMAIN,
    ECONOMICS_DOMAIN,
    COMPANY_DOMAIN,
    FUNDAMENTALS_DOMAIN,
    TECHNICALS_DOMAIN,
    COMMODITIES_DOMAIN,
    FX_DOMAIN,
    CRYPTO_DOMAIN,
)

# ---- DATASET NAMES ---- #
# Commodities
COMMODITIES_LIST_DATASET = "commodities-list"
COMMODITIES_PRICE_EOD_DATASET = "commodities-price-eod"

# Crypto
CRYPTO_LIST_DATASET = "crypto-list"
CRYPTO_PRICE_EOD_DATASET = "crypto-price-eod"

# FX
FX_LIST_DATASET = "fx-list"
FX_PRICE_EOD_DATASET = "fx-price-eod"

# ---- INSTRUMENT TYPES ---- #
INSTRUMENT_TYPE_EQUITY = "equity"
INSTRUMENT_TYPE_ETF = "etf"
INSTRUMENT_TYPE_INDEX = "index"
INSTRUMENT_TYPE_CRYPTO = "crypto"
INSTRUMENT_TYPE_FOREX = "forex"
INSTRUMENT_TYPES = [INSTRUMENT_TYPE_EQUITY, INSTRUMENT_TYPE_ETF, INSTRUMENT_TYPE_INDEX, INSTRUMENT_TYPE_CRYPTO, INSTRUMENT_TYPE_FOREX]

# ---- INSTRUMENT BEHAVIORS ---- #
INSTRUMENT_BEHAVIOR_CREATE = "create"
INSTRUMENT_BEHAVIOR_ENRICH = "enrich"
INSTRUMENT_BEHAVIOR_RELATIONSHIP = "relationship"
INSTRUMENT_BEHAVIORS = [INSTRUMENT_BEHAVIOR_CREATE, INSTRUMENT_BEHAVIOR_ENRICH, INSTRUMENT_BEHAVIOR_RELATIONSHIP]

# ---- EXECUTION PHASES ---- #
EXECUTION_PHASE_INSTRUMENT_DISCOVERY = "instrument_discovery"
EXECUTION_PHASE_DATA_ACQUISITION = "data_acquisition"
EXECUTION_PHASES = [EXECUTION_PHASE_INSTRUMENT_DISCOVERY, EXECUTION_PHASE_DATA_ACQUISITION]

# ---- DATA SOURCES ----#
FMP_DATA_SOURCE = "fmp"
AV_DATA_SOURCE = "alpha_vantage"
ALPACA_DATA_SOURCE = "alpaca"
SCHWAB_DATA_SOURCE = "schwab"
BIS_DATA_SOURCE = "bis"
FRED_DATA_SOURCE = "fred"
DATA_SOURCES: list = [FMP_DATA_SOURCE, AV_DATA_SOURCE, ALPACA_DATA_SOURCE, SCHWAB_DATA_SOURCE, BIS_DATA_SOURCE, FRED_DATA_SOURCE]

# ---- DATA SOURCE CONFIGURATION (used to configure settings for a given data source) ----#
RETRY_MAX_ATTEMPTS = "retry_max_attemps"
RETRY_BASE_DELAY = "retry_base_delay"
THROTTLE_MAX_CALLS_PER_MINUTE = "throttle_max_calls"
API_KEY = "API_KEY"  # this defines the label for the actual key in the .env file
BASE_URL = "base_url"
FMP_BASE_URL_STABLE: str = "https://financialmodelingprep.com/stable/"
DATA_SOURCES_CONFIG = {
    FMP_DATA_SOURCE: {
        RETRY_MAX_ATTEMPTS: 3,
        RETRY_BASE_DELAY: 0.5,
        THROTTLE_MAX_CALLS_PER_MINUTE: 3000,
        API_KEY: "FMP_API_KEY",
        BASE_URL: FMP_BASE_URL_STABLE,
    }
}

# ---- INSTRUMENT DATASETS ---- #
STOCK_LIST_DATASET = "stock-list"
ETF_LIST_DATASET = "etf-list"
INDEX_LIST_DATASET = "index-list"
CRYPTOCURRENCY_LIST_DATASET = "cryptocurrency-list"
FOREX_LIST_DATASET = "forex-list"
ETF_HOLDINGS_DATASET = "etf-holdings"

# ---- DATASETS (an internal label for a given dataset, which is represented as a table at the silver layer ----#
ECONOMICS_INDICATORS_DATASET = "economic-indicators"
TREASURY_RATES_DATASET = "treasury-rates"
MARKET_RISK_PREMIUM_DATASET = "market-risk-premium"
COMPANY_INFO_DATASET = "company-profile"
COMPANY_NOTES_DATASET = "company-notes"
COMPANY_PEERS_DATASET = "company-peers"
COMPANY_EMPLOYEES_DATASET = "company-employees"
COMPANY_MARKET_CAP_DATASET = "company-market-cap"
COMPANY_SHARES_FLOAT_DATASET = "company-shares-float"
COMPANY_OFFICERS_DATASET = "company-officers"
COMPANY_COMPENSATION_DATASET = "company-compensation"
COMPANY_DELISTED_DATASET = "company-delisted"
INCOME_STATEMENT_DATASET = "income-statement"
BALANCE_SHEET_STATEMENT_DATASET = "balance-sheet-statement"
CASHFLOW_STATEMENT_DATASET = "cashflow-statement"
LATEST_FINANCIALS_DATASET = "latest-financial-statements"
KEY_METRICS_DATASET = "key-metrics"
METRICS_RATIOS_DATASET = "metric-ratios"
KEY_METRICS_TTM_DATASET = "key-metrics-ttm"
RATIOS_TTM_DATASET = "ratios-ttm"
FINANCIAL_SCORES_DATASET = "financial-scores"
OWNER_EARNINGS_DATASET = "owner-earnings"
ENTERPRISE_VALUES_DATASET = "enterprise-values"
INCOME_STATEMENT_GROWTH_DATASET = "income-statement-growth"
BALANCE_SHEET_STATEMENT_GROWTH_DATASET = "balance-sheet-statement-growth"
CASHFLOW_STATEMENT_GROWTH_DATASET = "cashflow-statement-growth"
FINANCIAL_STATEMENT_GROWTH_DATASET = "finanical-statement-growth"
REVENUE_PRODUCT_SEGMENT_DATASET = "revenue-product-segementation"
REVENUE_GEOGRAPHIC_SEGMENT_DATASET = "revenue-geographic-segementation"
HISTORICAL_PRICE_EOD_FULL_DATASET = "technicals-historical-price-eod-full"
HISTORICAL_PRICE_EOD_NON_SPLIT_ADJUSTED_DATASET = "technicals-historical-price-eod-non-split-adjusted"
HISTORICAL_PRICE_EOD_DIVIDEND_ADJUSTED_DATASET = "technicals-historical-price-eod-dividend-adjusted"
TECHNICALS_SMA_20_DATASET = "technicals-sma-20"
TECHNICALS_SMA_50_DATASET = "technicals-sma-50"
TECHNICALS_SMA_200_DATASET = "technicals-sma-200"
TECHNICALS_EMA_12_DATASET = "technicals-ema-12"
TECHNICALS_EMA_26_DATASET = "technicals-ema-26"
TECHNICALS_EMA_50_DATASET = "technicals-ema-50"
TECHNICALS_EMA_200_DATASET = "technicals-ema-200"
TECHNICALS_WMA_20_DATASET = "technicals-wma-20"
TECHNICALS_WMA_50_DATASET = "technicals-wma-50"
TECHNICALS_WMA_200_DATASET = "technicals-wma-200"
TECHNICALS_DEMA_12_DATASET = "technicals-dema-12"
TECHNICALS_DEMA_26_DATASET = "technicals-dema-26"
TECHNICALS_DEMA_50_DATASET = "technicals-dema-50"
TECHNICALS_DEMA_200_DATASET = "technicals-dema-200"
TECHNICALS_TEMA_20_DATASET = "technicals-tema-20"
TECHNICALS_RSI_14_DATASET = "technicals-rsi-14"
TECHNICALS_RSI_7_DATASET = "technicals-rsi-7"
TECHNICALS_STANDARD_DEVIATION_20_DATASET = "technicals-standard-deviation-20"
TECHNICALS_WILLIAMS_14_DATASET = "technicals-williams-14"
TECHNICALS_ADX_14_DATASET = "technicals-adx-14"

# ---- MARKET DATASETS ---- #
MARKET_COUNTRIES_DATASET = "market-countries"
MARKET_EXCHANGES_DATASET = "market-exchanges"
MARKET_SECTORS_DATASET = "market-sectors"
MARKET_INDUSTRIES_DATASET = "market-industries"
MARKET_SECTOR_PERFORMANCE_DATASET = "market-sector-performance"
MARKET_INDUSTRY_PERFORMANCE_DATASET = "market-industry-performance"
MARKET_SECTOR_PE_DATASET = "market-sector-pe"
MARKET_INDUSTRY_PE_DATASET = "market-industry-pe"
MARKET_HOURS_DATASET = "market-hours"
MARKET_HOLIDAYS_DATASET = "market-holidays"

DATASETS: list = [
    ECONOMICS_INDICATORS_DATASET,
    TREASURY_RATES_DATASET,
    MARKET_RISK_PREMIUM_DATASET,
    COMPANY_INFO_DATASET,
    COMPANY_NOTES_DATASET,
    COMPANY_PEERS_DATASET,
    COMPANY_EMPLOYEES_DATASET,
    COMPANY_MARKET_CAP_DATASET,
    COMPANY_SHARES_FLOAT_DATASET,
    COMPANY_OFFICERS_DATASET,
    COMPANY_COMPENSATION_DATASET,
    COMPANY_DELISTED_DATASET,
    INCOME_STATEMENT_DATASET,
    BALANCE_SHEET_STATEMENT_DATASET,
    CASHFLOW_STATEMENT_DATASET,
    LATEST_FINANCIALS_DATASET,
    KEY_METRICS_DATASET,
    METRICS_RATIOS_DATASET,
    KEY_METRICS_TTM_DATASET,
    RATIOS_TTM_DATASET,
    FINANCIAL_SCORES_DATASET,
    OWNER_EARNINGS_DATASET,
    ENTERPRISE_VALUES_DATASET,
    INCOME_STATEMENT_GROWTH_DATASET,
    BALANCE_SHEET_STATEMENT_GROWTH_DATASET,
    CASHFLOW_STATEMENT_GROWTH_DATASET,
    FINANCIAL_STATEMENT_GROWTH_DATASET,
    REVENUE_PRODUCT_SEGMENT_DATASET,
    REVENUE_GEOGRAPHIC_SEGMENT_DATASET,
    HISTORICAL_PRICE_EOD_FULL_DATASET,
    HISTORICAL_PRICE_EOD_NON_SPLIT_ADJUSTED_DATASET,
    HISTORICAL_PRICE_EOD_DIVIDEND_ADJUSTED_DATASET,
    TECHNICALS_SMA_20_DATASET,
    TECHNICALS_SMA_50_DATASET,
    TECHNICALS_SMA_200_DATASET,
    TECHNICALS_EMA_12_DATASET,
    TECHNICALS_EMA_26_DATASET,
    TECHNICALS_EMA_50_DATASET,
    TECHNICALS_EMA_200_DATASET,
    TECHNICALS_WMA_20_DATASET,
    TECHNICALS_WMA_50_DATASET,
    TECHNICALS_WMA_200_DATASET,
    TECHNICALS_DEMA_12_DATASET,
    TECHNICALS_DEMA_26_DATASET,
    TECHNICALS_DEMA_50_DATASET,
    TECHNICALS_DEMA_200_DATASET,
    TECHNICALS_TEMA_20_DATASET,
    TECHNICALS_RSI_14_DATASET,
    TECHNICALS_RSI_7_DATASET,
    TECHNICALS_STANDARD_DEVIATION_20_DATASET,
    TECHNICALS_WILLIAMS_14_DATASET,
    TECHNICALS_ADX_14_DATASET,
    STOCK_LIST_DATASET,
    ETF_LIST_DATASET,
    INDEX_LIST_DATASET,
    CRYPTOCURRENCY_LIST_DATASET,
    FOREX_LIST_DATASET,
    ETF_HOLDINGS_DATASET,
    MARKET_COUNTRIES_DATASET,
    MARKET_EXCHANGES_DATASET,
    MARKET_SECTORS_DATASET,
    MARKET_INDUSTRIES_DATASET,
    MARKET_SECTOR_PERFORMANCE_DATASET,
    MARKET_INDUSTRY_PERFORMANCE_DATASET,
    MARKET_SECTOR_PE_DATASET,
    MARKET_INDUSTRY_PE_DATASET,
    MARKET_HOURS_DATASET,
    MARKET_HOLIDAYS_DATASET,
    COMMODITIES_LIST_DATASET,
    COMMODITIES_PRICE_EOD_DATASET,
    CRYPTO_LIST_DATASET,
    CRYPTO_PRICE_EOD_DATASET,
    FX_LIST_DATASET,
    FX_PRICE_EOD_DATASET,
]

# ---- CADENCE MODE ---- #
INTERVAL_CADENCE_MODE = "interval"
CALENDAR_CADENCE_MODE = "calendar"
CADENCES = [INTERVAL_CADENCE_MODE, CALENDAR_CADENCE_MODE]

# ---- DAYS OF WEEK ---- #
MONDAY = "mon"
TUESDAY = "tues"
WEDNESDAY = "wed"
THURSDAY = "thurs"
FRIDAY = "fri"
SATURDAY = "sat"
SUNDAY = "sun"
DAYS_OF_WEEK = [
    MONDAY,
    TUESDAY,
    WEDNESDAY,
    THURSDAY,
    FRIDAY,
    SATURDAY,
    SUNDAY,
]
DAYS_OF_WEEK_BY_INDEX = {
    0: MONDAY,
    1: TUESDAY,
    2: WEDNESDAY,
    3: THURSDAY,
    4: FRIDAY,
    5: SATURDAY,
    6: SUNDAY,
}

# ---- QUERY VAR PLACEHOLDERS ----#
TICKER_PLACEHOLDER = "__ticker__"
FROM_DATE_PLACEHOLDER = "__from__"
TO_DATE_PLACEHOLDER = "__to__"
FROM_ONE_MONTH_AGO_PLACEHOLDER = "__from_one_month_ago__"
DATE_PLACEHOLDER = "__date__"
LIMIT_PLACEHOLDER = "__limit__"
PERIOD_PLACEHOLDER = "__period__"

# --- reporting periods ---
PERIOD_ANNUAL = "annual"

# --- DATA FOLDERS ---
DATA_ROOT_FOLDER = os.environ.get("DATA_ROOT_FOLDER", "c:/sb/SBFoundation/data")
REPO_ROOT_FOLDER = os.environ.get("REPO_ROOT_FOLDER", "c:/sb/SBFoundation")
BRONZE_FOLDER = "bronze"
DUCKDB_FOLDER = "duckdb"
DUCKDB_FILENAME = "SBFoundation.duckdb"
MIGRATIONS_FOLDER = "db/migrations"
LOG_FOLDER = "logs"
DATASET_KEYMAP_FOLDER = "config"
DATASET_KEYMAP_FILENAME = os.environ.get("DATASET_KEYMAP_FILENAME", "dataset_keymap.yaml")

# --- FMP PRICING TIERS ---
FMP_BASIC_PLAN = "basic"
FMP_STARTER_PLAN = "starter"
FMP_PREMIUM_PLAN = "premium"
FMP_ULTIMATE_PLAN = "ultimate"
FMP_PLANS = [FMP_BASIC_PLAN, FMP_STARTER_PLAN, FMP_PREMIUM_PLAN, FMP_ULTIMATE_PLAN]

FROM_DATE = "1980-01-01"


# --- HTTP calls, Retry and Throttle settings ---
RETRY_MAX_ATTEMPS = 3
RETRY_BASE_DELAY = 0.5
THROTTLE_PERIOD_SECONDS = 60
THROTTLE_MAX_CALLS = 60
CONNECT_TIMEOUT = 5
READ_TIMEOUT = 30
